### ISSUE TITLE
S3 File Upload hashes - implicit rather than explicit?

### ISSUE THREAD

**Issue by askoufis** [SEEK-Org/evaporate#8]
With the current behaviour of the S3 File Upload feature when hashing is enabled, there is some redundancy int he config.

The file paths must be specified like this:

```
s3upload:
- name: bucket1
  hash: true
  paths:
    - file1.txt
    - file2.txt
    - myFolder
- name: bucket1
  hash: false
  paths:
    - file3.txt
```

Then to actually make use of any of the hashes (and why would you hash them if you're not going to then use those hashes?) you must add them all individually to the stack parameters like so:

```
parameters:
  123412341234:
    FileHash: ${hash.path/to/file.txt}
```

What if we made the latter part unnecessary by automatically including all hashed paths in the stack parameters? The only issue with this is that parameter keys must be alphanumeric so having the key as the file path wouldn't work. There might be some way to normalise the file paths to alphanumeric characters, maybe by just removing all `/` and `.` characters. Thoughts?
